### ISSUE TITLE
maybe merge the two plugins

### ISSUE THREAD

**Issue by fossfreedom** [radus/rhythmbox_stop_after_track#1]
looks like an interesting plugin.

Since you say its similar to the other plugin - any chance of looking to merge the two plugins?

thanks

**Comment by radus** [comment]
Yes, I've thought about this also. I've sent an email to the owner of the StopAfterCurrentTrack plugin to see if it's ok also from his side to merge the two in a single repository.

**Comment by fossfreedom** [comment]
Its GPL code - as long as you acknowledge the owner in the copyright statement, its ok to merge the code i.e. you dont have to wait for permission.  Hope that helps.

**Comment by radus** [comment]
I've added the other plugin to this repository, so now you can get both of them from one location.
